# Generated by Django 5.2 on 2025-04-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='urls',
            field=models.URLField(blank=True, null=True),
        ),
    ]
